### ISSUE TITLE
Build out Sidebars for sections on the site

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#26]

**Comment by imbradmiller** [comment]
Hey @matthewsimo did you complete this?

**Comment by matthewsimo** [comment]
Sidebars are created, but I mentioned in the meeting on Tuesday how I'm still not sure on how we're going to be handling passing the widget data back and forth for some of them, so that part of it isn't really clear yet. The angular directives that house the widgets are completed, but I haven't declared/registered the widgets for WP yet. Will go ahead and close since those parts live in different tix.

**Comment by imbradmiller** [comment]
Right on. Thanks, Simo.
