### ISSUE TITLE
Create WP widgets for each of the widgets in the static prototypes

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#29]
After reviewing the prototype I think I count 5 widgets that need to be created. These are kind of like "sugar on top" so I'm not of the opinion that we need to do all of these for launch. But, here are the one's I've identified:

(See updated list of widgets in thread.)

We might want to revisit each and assign a priority. Also some are confusing and might be worth clarifying... Thoughts?

**Comment by imbradmiller** [comment]
Not directly dependent  on #26, but #26 should be done first.

**Comment by matthewsimo** [comment]
So, I wanted to give a breakdown since these have changed from initial prototype. Reasons vary from "in the prototype they were actually the same module just with different titles" to "due to how the github api returns requests, we have to split this one.." All that to say:

These are the widgets IP is providing (at least at launch):
- [x] IssuePress Message Widget (corresponds to the "welcome text" item above)
- [x] IssuePress Recent Comment Activity Widget (Shows context aware recent comments)
- [x] IssuePress Recent Activity Widget (Shows recent issue activity, according to github issue api (commented on, opened, closed..) for current context)
- [x] IssuePress Release Widget (Shows recent section level activity, according to undocumented github releases API - which is currently broken )
- [x] IssuePress Sections List Widget (Shows the list of sections)

All of these widgets are created and showing in the admin in the ng-widget branch, just finishing the angular template output for them. Thanks, let me know if you have any questions/concerns.

Removing this one: (Putting on ice for time being)
IssuePress Recent Issues Widget (Shows a context aware list of issues and their initial comment.)

**Comment by matthewsimo** [comment]
All the widgets are created and are rendering angular components. Will keep this open for the time being as QA is hard to do without #56 being done. Thanks.

**Comment by matthewsimo** [comment]
Will close this ticket since it's "completed" but we need to do testing and so I'm assuming we'll catch stuff in QA..

**Comment by issuepressapp** [comment]
Close it dawg!

---

IssuePress Data:

username: "chriswallace"
email: "chris@liftux.com"
firstname: "Chris"
lastname: "Wallace"
display_name: "Chris Wallace"
ID: "1"
gravatar_id: "de5e8c95f06ac55e9b297c7c3e1de33b"

Sent via [IssuePress](http://issuepress.co)
