### ISSUE TITLE
Where is the follow feature for following an issue?

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#89]
Is this something we cut from scope? I have it in the documentation but don't see it in the plugin.

**Comment by matthewsimo** [comment]
If I recall, I think this feature was postponed until we built out more robust user features. Since this is a completely custom feature it doesn't use the github api at all (it's all custom code specific to IP). It'll require new api endpoint, new custom user meta fields for saving, updating, and managing followed issues, and new interface code... hence the postponement..

**Comment by imbradmiller** [comment]
Cool. I'll label this as an enhancement and we'll place it as a v2 or v1.5 or whatever.
